---
sidebar: sidebar
permalink: create-azure-connector-user-consent-snapcenter-service.html
keywords: azure, connector, cloud central, snapcenter service, user consent, tenant admin, create connector, enable, disable, azure marketplace
summary: Create an Azure Connector for SnapCenter Service.
---

= Create an Azure Connector for SnapCenter Service
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

An Account Admin should deploy a Connector before you can use the Cloud Manager features. The Connector enables Cloud Manager to manage resources and processes within your public cloud environment.

By default, you can create an Azure Connector from Azure Marketplace. While performing the steps to link:task_launching_azure_mktp.html[create the connector from Azure marketplace], you should remember the following:

* Wherever Cloud Manager for Cloud Volumes ONTAP is specified, the same can be leveraged for SnapCenter Service.
* For the Cloud Manager Name specify your Connector VM name for better identification. This will be shown as connector name in the Cloud Manager UI.
* If you have configured the Connector without public IP or configured a firewall, you should have a jump host to connect to the Connector machine.

If you have https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-user-consent?tabs=azure-portal#user-consent-settings[user consent^] enabled in your Azure Active Directory or if your tenant admin can provide the consent, you can create the Connector from Cloud Manager UI.

== User consent is enabled

If the user consent is enabled in your Azure active directory, link:task_creating_connectors_azure.html[create the Connector from Cloud Manager].

== User consent is disabled

. Perform one of the following:
* If the admin consent workflow is configured in your active directory, you should https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-admin-consent-workflow#how-users-request-admin-consent[request for admin consent^].
* If the admin consent workflow is not configured, you should:
.. https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent#construct-the-url-for-granting-tenant-wide-admin-consent[Construct the URL for granting tenant-wide admin consent^].
+
[NOTE]
Specify the clientID as _989efff4-9a9e-46fa-9f17-de39e15714f9_. This is the Cloud Manager Azure application ID named in the Cloud Manager wizard.

.. Ask your tenant admin to run the URL in a browser and provide his consent.
+
The displayed errors can be ignored by your Admin.

. link:task_creating_connectors_azure.html[Create the Connector from Cloud Manager].

[IMPORTANT]
The username and password or the key that was provided while creating the Connector would be required to connect to the machine
