---
sidebar: sidebar
permalink: reference_networking.html
keywords: networking overview, networking requirements, endpoints, urls
summary: Before users log in to Cloud Manager, you'll need to ensure that their web browsers can access specific endpoints. After that, you need to verify networking requirements for the specific type of working environment that you create and any services that you enable.
---

= Networking overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Before users log in to Cloud Manager, you'll need to ensure that their web browsers can access specific endpoints. After that, you need to verify networking requirements for the specific type of working environment that you create and any services that you enable.

== Endpoints accessed from your web browser

Users must access Cloud Manager from a web browser. The machine running the web browser must have connections to the following endpoints:

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

| \http://cloudmanager.netapp.com | Your web browser contacts this URL when using the SaaS UI.

| The Connector’s IP address
a| In most cases, you should work with Cloud Manager from the SaaS UI, but if you need to use the link:concept_connectors.html#using-multiple-connectors-with-the-same-working-environment[local UI], then you must enter the host’s IP address from a web browser to load the Cloud Manager console.

Depending on the connectivity to your cloud provider, you can use the private IP or a public IP assigned to the host:

- A private IP works if you have a VPN and direct connect access to your virtual network
- A public IP works in any networking scenario

In any case, you should secure network access by ensuring that security group rules allow access from only authorized IPs or subnets.

a|
AWS services (amazonaws.com):

*	CloudFormation
*	Elastic Compute Cloud (EC2)
*	Key Management Service (KMS)
*	Security Token Service (STS)
*	Simple Storage Service (S3)

The exact endpoint depends on the region in which you deploy Cloud Volumes ONTAP. https://docs.aws.amazon.com/general/latest/gr/rande.html[Refer to AWS documentation for details.^]

| Required to deploy a Connector from Cloud Manager in AWS.

|
\https://management.azure.com
\https://login.microsoftonline.com
| Required to deploy a Connector from Cloud Manager in most Azure regions.

|
\https://management.microsoftazure.de
\https://login.microsoftonline.de
| Required to deploy a Connector from Cloud Manager in Azure Germany regions.

|
\https://management.usgovcloudapi.net
\https://login.microsoftonline.com
| Required to deploy a Connector from Cloud Manager in Azure US Gov regions.

|
\https://www.googleapis.com

| Required to deploy a Connector from Cloud Manager in Google Cloud.

| \https://signin.b2c.netapp.com
| Required to update NSS credentials or to add new NSS credentials to Cloud Manager.

|
\https://auth0.com
\https://cdn.auth0.com
\https://services.cloud.netapp.com
| Your web browser connects to these endpoints for centralized user authentication through NetApp Cloud Central.

| \https://widget.intercom.io
| For in-product chat that enables you to talk to NetApp cloud experts.

|===

== Index of networking requirements

* link:reference_networking_cloud_manager.html[Connectors]
* link:reference_networking_aws.html[Cloud Volumes ONTAP for AWS]
* link:reference_networking_azure.html[Cloud Volumes ONTAP for Azure]
* link:reference_networking_gcp.html[Cloud Volumes ONTAP for GCP]
* link:task_replicating_data.html[Data replication between ONTAP systems]
* link:task_getting_started_compliance.html[Cloud Data Sense for Cloud Volumes ONTAP, on-premises ONTAP, or Azure NetApp Files]
* link:task_scanning_s3.html[Cloud Data Sense for Amazon S3]
* link:task_scanning_object_storage.html[Cloud Data Sense for generic S3 object storage]
* link:task_scanning_file_shares.html[Cloud Data Sense for non-NetApp NFS or CIFS file shares]
* link:task_scanning_databases.html[Cloud Data Sense for databases]
* link:task_scanning_onedrive.html[Cloud Data Sense for OneDrive accounts]
* link:task_discovering_ontap.html[On-prem ONTAP clusters]
** link:task_tiering_onprem_aws.html[Data tiering from ONTAP clusters to Amazon S3]
** link:task_tiering_onprem_azure.html[Data tiering from ONTAP clusters to Azure Blob storage]
** link:task_tiering_onprem_gcp.html[Data tiering from ONTAP clusters to Google Cloud Storage]
** link:task_tiering_onprem_storagegrid.html[Data tiering from ONTAP clusters to StorageGRID]
** link:task_backup_from_onprem.html[Data backup from ONTAP clusters to Amazon S3 or Azure Blob storage]
